### ISSUE TITLE
What is the next step after getting the ranking_results?

### ISSUE THREAD

**Issue by happygirlzt** [irving-muller/soft_alignment_model_bug_deduplication#4]
Hi Irving! (Somehow, I need to replicate your work again...) I found I can finish running your approach by the command provided in the README, e.g., `python3 experiments/sabd.py -F HOME_DIR/experiments with HOME_DIR/duplicate-bug-report/json_parameters/sabd_open_office_test.json "recall_rate.window=365"`
Then, a text file is generated under the ranking_result folder. Just like the figure below:
<img width="371" alt="Screenshot 2021-06-03 at 10 59 00" src="https://user-images.githubusercontent.com/15061984/120580438-ca4c5400-c45b-11eb-9115-3c080094c209.png">

However, I'm not sure what is the next step for me to get the recall rate or MAP. How should I interpret this result file? Any command? Many thanks in advance!

**Comment by irving-muller** [comment]
Hi @happygirlzt! 

`experiments/sabd.py` should print the MAP and recall rate values. The generated file was only used for debugging since it contains report id and similarity scores in the ranked list. Maybe, you could use this file to compute the recall rate@k and MAP. Let me know if you need a script for that.

Note: the positions of correct candidates for each query are printed as well. You could also use it to compute the metric values.

**Comment by happygirlzt** [comment]
Hi @irving-muller!
Yes, I save the log printed by `experiments/satd.py` and saw the results. 🥰  Many thanks for your help! ❤️
As I prepare to apply your approach satd on new datasets, I have a hard time understanding the relationship between pymongo dump data, e.g., OpenOffice, and the database json file, e.g., `open_office_initial.json`. I searched the code but cannot understand where the `open_office_initial.json` comes from. 
I think the information carried by pymongo dump and `BTS_initial.json` should be the same, as they represent the same BTS. I wonder whether I can only use BTS_initial.json, without using PyMongo dump to save the bug reports data first.
Thank you so much as usual. 👍 Have a nice weekend!

**Comment by irving-muller** [comment]
I am glad to hear that you could get the results.  :) 

As mentioned in the **README.md**, all the files `BTS_initial.json` are generated from the original dataset provided by Lazar. For instance, the following command runs `create_dataset_our_methodology.py` and creates `open_office_initial.json` from the data in the database `openOffice`.

`python data/create_dataset_our_methodology.py --database openOffice --collection initial --bug_data DATASET_DIR/open_office_2001-2008_2010/open_office_initial.json --training  DATASET_DIR/open_office_2001-2008_2010/training_split_open_office.txt --validation  DATASET_DIR/open_office_2001-2008_2010/validation_open_office.txt --test DATASET_DIR/open_office_2001-2008_2010/test_open_office.txt --date="2008/01/01" --date_threshold="2010/12/31" --no_tree --dev_perc=0.05 
`

> I think the information carried by pymongo dump and BTS_initial.json should be the same, as they represent the same BTS. I wonder whether I can only use BTS_initial.json, without using PyMongo dump to save the bug reports data first.

They are almost identical. We apply some preprocessing steps to create the json file:

- We check if the master report exists in the database. If not, we choose the oldest one to be the master
- We guarantee that the first bug submitted in a bucket is always the master report.
- We remove cycles
- We guarantee that a bug report belongs to only one bucket.

> I wonder whether I can only use BTS_initial.json, without using PyMongo dump to save the bug reports data first.

Yes, you could do that.

**Comment by happygirlzt** [comment]
Hi @irving-muller ! Thanks for your help!
I have now managed to generate the `BTS_initial.json`. However, it can only generate `training_split_BTS.txt`, `validation_BTS.txt` and `test_BTS.txt`. I did not figure out which script to generate the `training_BTS.txt`. Did you simply combine `training_split_BTS.txt` and `validation_BTS.txt`? 
Also, I found a potential typo in README, should it be `python data/generate_pairs_triplets.py  --bug_data dataset/mozilla/one-year-mozilla-v5.json --dataset dataset/mozilla/training_mozilla.txt --n 1 --type random`? Maybe wrong file here.
<img width="876" alt="Screenshot 2021-06-10 at 09 13 15" src="https://user-images.githubusercontent.com/15061984/121449296-194e3800-c9cc-11eb-8368-50dff4ae0b1d.png">

**Comment by irving-muller** [comment]
Hello @happygirlzt. 

Yes that is correct. You can concatenate training_split and validation using this [script](https://github.com/irving-muller/soft_alignment_model_bug_deduplication/blob/master/util/join_training_validation.py). You can find the meaning of each argument in the code. Sorry for the lacking of documentation.

> Also, I found a potential typo in README, should it be python data/generate_pairs_triplets.py --bug_data dataset/mozilla/one-year-mozilla-v5.json --dataset dataset/mozilla/training_mozilla.txt --n 1 --type random? Maybe wrong file here

Oh, you are correct. I will fix this. Thank you! :)

**Comment by happygirlzt** [comment]
Dear @irving-muller! Great, many thanks for your patience and tremendous help! :) Have a wonderful Friday and weekend ahead!
